language: java
jdk:
  - openjdk8
branches:
  only:
    - master
# Travis Ci SERVER HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: './gradlew clean build'

before_install:
  - 'chmod +x gradlew'

before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider:  s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: kjp0602-springboot-webservice-build
    region: us-east-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    buket: kjp0602-springboot-webservice-build
    key: springboot-webservice.zip

    bundle_type: zip
    application: springboot-webservice
    deployment_group: springboot-webservice-group

    region: us-east-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - 'kjp0602@gmail.com'